stocks:
  - symbol: FSKAX
    target_percentage: 67
    description: Total US Market
  - symbol: FTIHX
    target_percentage: 17
    description: Total International Market
  - symbol: FXNAX
    target_percentage: 15
    description: Total Bond Market
  - symbol: FBTC
    target_percentage: 0.8
    description: Bitcoin
  - symbol: FETH
    target_percentage: 0.2
    description: Ethereum
